# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: CI
  displayName: 'Continuous Integration'

  jobs:
  - job: Build
    displayName: 'Build and Test'

    steps:

    - script: echo "Iniciando CI"
      displayName: 'Iniciar pipeline'

    - script: |
        cd Front
        npm ci
        npm run build
      displayName: 'Build Frontend'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'Front/dist'
        ArtifactName: 'frontend'
        publishLocation: 'Container'
      displayName: 'Publicar Artifact Frontend'

    - script: |
        cd back
        chmod +x mvnw
        ./mvnw test
        ./mvnw package
      displayName: 'Build Backend'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'back/target'
        ArtifactName: 'backend'
        publishLocation: 'Container'
      displayName: 'Publicar Artifact Backend'
## DEPLOYS
- stage: CD
  displayName: 'Continuous Delivery'

## VALIDAMOS QUE SE EJECUTE PRIMERO LOS TEST Y BUIDS CORRECTAMENTE Y EJECUTAMOS
  dependsOn: CI
  condition: succeeded()

## DEPLOY BACKEND
  jobs:
  - job: DeployBackend
    displayName: 'Deploy Backend'

    steps:
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'backend'
          downloadPath: '$(System.ArtifactsDirectory)'
        displayName: 'Descargar Artifact Backend'
      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'sc-lavoratorio-azure'
          appType: 'webAppLinux'
          appName: 'lavoratorio-backend'
          package: '$(System.ArtifactsDirectory)/backend/*.jar'
        displayName: 'Deploy Backend'

## DEPLOY FRONTEND
  - job: DeployFrontend
    displayName: 'Deploy Frontend'
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'frontend'
        downloadPath: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Descargar Artifact Frontend'

    - script: |
        echo "Contenido del artifact:"
        find "$(Build.ArtifactStagingDirectory)" -maxdepth 3 -type f
      displayName: 'Verificar archivos Frontend'

    - script: |
        mkdir -p $(System.DefaultWorkingDirectory)/frontend
        cp -r $(Build.ArtifactStagingDirectory)/frontend/* $(System.DefaultWorkingDirectory)/frontend/
      displayName: 'Copiar build a working directory'

    - task: AzureStaticWebApp@0
      inputs:
        app_location: 'frontend'
        output_location: ''
        skip_app_build: true
        azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
      displayName: 'Deploy Frontend'